# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required
# https://github.com/docker/awesome-compose/tree/master/postgresql-pgadmin
services:
  db-live:
    container_name: postgres-live
    image: postgres:15-alpine
    user: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
     - ${POSTGRES_PORT_LIVE}:5432
    volumes:
      - "data-db-live:/var/lib/postgresql/data"
      - "./src/healthchecks:/healthchecks"
      - "./src/main/resources/db/seed/init_database_v1.sh:/docker-entrypoint-initdb.d/init_database.sh"
    restart: always
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
  db-dev:
    container_name: postgres-dev
    image: postgres:15-alpine
    user: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
     - ${POSTGRES_PORT_DEV}:5432
    volumes:
      - "data-db-dev:/var/lib/postgresql/data"
      - "./src/healthchecks:/healthchecks"
    restart: always
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
volumes:
  data-db-live:
  data-db-dev: